language: csharp
solution: UnitatoBot/UnitatoBot.sln
branches:
  only:
    - master
deploy:
  provider: releases
  api_key: ${GUTHUB_OAUTH_KEY}
  file: UnitatoBot\bin\Debug"
  skip_cleanup: true
  on:
    tags: true